<?php

return [
    'learning_programs' => 'LEARNING PROGRAMS',
    'minna_no' => 'Once you’ve learnt Japanese, you’ve heard about Minna no Nihongo textbook. This is the standard textbook for cultivating communication skills by learning grammar and basic vocabulary as well as getting to know daily conversations in different situations.  And Minna no Nihongo Chuukyuu appeared for those students have already finished the primary version of Minna no Nihongo and desire to upgrade to the Intermediate level, to enhance the knowledge and realistic practicing skills such as listening, speaking, reading and writing. The Intermediate Minna no Nihongo can be considered as The Highest Appreciating Japanese Textbook lately since it included all skills and not only guiding self-learning students but also be a great book for teaching.',
    'namerata' => 'If you reach the top notch of writing skills but still feel awkward with communicating and crave for mastering conversation language, Nameraka Nihonggo will be your textbook. You will learn essential rules of speaking Japanese through common conversations. Thenceforth you can practice and be able to improve your speaking skill faster. The book (including 3 parts with 23 detailed and clear sessions) is covered by realistic situation with simple and natural language. Purpose of the book is elevating communication skills and expanding the vocabulary in order to speak Japanese in real life naturally like the Japanese natives. Accomplishing the course, you will be successfully in Japanese communicating and easily listening and actually understanding the Japanese natives’ conversations in real life.',
    'seikatsu' => 'This is the textbook for those who are interested in studying daily Japanese conversations and want to speak Japanese in real life naturally as natives.<br/>It is divided into 7 lessons with detailed sessions, includes daily topics such as greeting, introduce yourself, realistic situations (shopping, asking a favor…)<br/>With essential vocabularies and structures, this book will help you improve your communication skills and you can easily communicate confidently with Japanese. Moreover, it distinguishes confused grammar structures so you can understand and use them correctly in every single context.<br/>This a very useful material for studying Japanese communication skills. You can speak Japanese more confidently and flexibility in studying, workplace and daily life.',
    'short_minna_no' => 'Once you’ve learnt Japanese, you’ve heard about Minna no Nihongo textbook. This is the standard textbook for cultivating communication skills ',
    'short_namerata' => 'If you reach the top notch of writing skills but still feel awkward with communicating and crave for mastering conversation language ',
    'short_seikatsu' => 'This is the textbook for those who are interested in studying daily Japanese conversations and want to speak Japanese in real life naturally as natives.',
    
];

