<?php

return [
    'learning_programs' => 'CHƯƠNG TRÌNH HỌC',
    'minna_no' => 'Đối với người học tiếng Nhật thì chắc chắn không ai là không biết đến bộ giáo trình Minna no Nihongo, bởi nó là một giáo trình tiêu chuẩn trong trau dồi các kỹ năng đàm thoại thực tế của người học thông qua việc học ngữ pháp và từ vựng cơ bản, cũng như tiếp xúc với cuộc trò chuyện hàng ngày ở các tình huống khác nhau. Và giáo trình Minna no Nihongo Chuukyuu ra đời để đáp ứng nhu cầu của những người đã học xong Minna no Nihongo sơ cấp và đang muốn học lên Trung cấp, những người muốn nâng cao kiến thức và luyện tập một cách thực tế tất cả các kỹ năng như nghe, nói, đọc và viết. Giáo trình Minna no nihongo trung cấp có thể xem là cuốn giáo trình tiếng Nhật được đánh giá cao nhất hiện nay bởi nó tổng hợp tất cả các kỹ năng và hướng dẫn người học tự học, cũng như dành cho việc giảng dạy theo những trình tự nhất định.',
    'namerata' => 'Nếu bạn đã ổn trong văn viết nhưng vẫn còn chưa thành thục trong giao tiếp tình huống, và có nguyện vọng muốn học được ngôn ngữ đàm thoại, thì đây là giáo trình dành cho bạn. Bằng các mẫu hội thoại thông dụng, bạn sẽ hiểu các quy luật trong văn nói của tiếng Nhật, các quy tắc cần thiết cho đàm thoại. Để từ đó luyện tập và có thể cải thiện khả năng nói tiếng Nhật của mình trong thời gian ngắn. Xuyên suốt trong giáo trình (gồm 3 phần với 23 mục nhỏ rất chi tiết và rõ ràng ) là những tình huống thực tế, sử dụng ngôn ngữ đơn giản và gần gũi, tự nhiên.. Mục đích là thông qua đó chúng ta sẽ nâng cao được khả năng giao tiếp và mở rộng được vốn từ vựng để có thể nói tiếng Nhật trong đời thường một cách tự nhiên như người Nhật bản xứ. Kết thúc chương trình học, bạn sẽ thành công trong giao tiếp tiếng Nhật. Bên cạnh đó còn có thể nghe và hiểu được các cuộc đàm thoại mà người Nhật nói chuyện với nhau trên thực tế.',
    'seikatsu' => 'Là giáo trình dành cho những bạn có hứng thú với tiếng nhật, những bạn cần tiếng nhật trong giao tiếp hàng ngày, và đặc biệt dành cho các bạn nào muốn trong một thời gian ngắn có thể sử dụng tiếng nhật vào các tình huống thực tế một cách nhanh chóng. Giáo trình chia làm 7 bài với nhiều phần nhỏ, bao gồm những chủ đề gắn bó với cuộc sống thường ngày như: giao tiếp gặp gỡ lần đầu, tự giới thiệu bản thân cho đến những tình huống thiết thực như mua sắm, nhờ vả ai đó v.v...<br/>Ngoài việc cung cấp những kiến thức giúp bạn nắm bắt những mẫu câu, từ vựng cần thiết để nâng cao khả năng giao tiếp bằng tiếng Nhật, dễ dàng áp dụng vào các tình huống và giao tiếp với người Nhật một cách tự tin; bên cạnh đó còn giải thích, phân biệt những mẫu ngữ pháp thông dụng để bạn có thể sử dụng đúng trong từng ngữ cảnh khác nhau.<br/>Đây là một giáo trình giao tiếp tiếng Nhật vô cùng bổ ích, giúp bạn tiếp cận với ngôn ngữ của đất nước mặt trời mọc dễ dàng hơn bao giờ hết và có thể sử dụng tiếng Nhật một cách linh hoạt trong cuộc sống, học tập cũng như trong công việc.',
    'short_minna_no' => 'Đối với người học tiếng Nhật thì chắc chắn không ai là không biết đến bộ giáo trình Minna no Nihongo bởi nó là một giáo trình tiêu chuẩn...',
    'short_namerata' => 'Nếu bạn đã ổn trong văn viết nhưng vẫn còn chưa thành thục trong giao tiếp tình huống, và có nguyện vọng muốn học được ngôn ngữ đàm thoại...',
    'short_seikatsu' => 'Là giáo trình dành cho những bạn có hứng thú với tiếng nhật, những bạn cần tiếng nhật trong giao tiếp hàng ngày...',
    
];

